name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongo:
        image: bitnami/mongodb
        ports:
          - 27017:27017
        env:
          MONGODB_USERNAME: docker
          MONGODB_PASSWORD: docker
          MONGODB_DATABASE: clean-node-api

    strategy:
      matrix:
        node-version: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- -c jest-unit-config.ts

      - name: Run E2E Tests
        run: npm test -- -c jest-integration-config.ts
        env:
          JWT_SECRET: t8731hda=19kj
          MONGO_URL: "mongodb://docker:docker@localhost:27017/clean-node-api"

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
