name: Run E2E Tests

on: [push, pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      mongo:
        image: bitnami/mongodb
        ports:
          - 27017:27017
        env:
          MONGODB_USERNAME: docker
          MONGODB_PASSWORD: docker
          MONGODB_DATABASE: clean-node-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm test -- --config=jest-integration-config.ts
        env:
          JWT_SECRET: t8731hda=19kj
          MONGO_URL: "mongodb://docker:docker@localhost:27017/clean-node-api"
