name: Run Unit Tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- -c jest-unit-config.ts